modLoader = "javafml"
loaderVersion = "[46,)"
#issueTrackerURL = ""
license = "LGPLv3"

[[mods]]
modId = "vivecraft"
version = "${version}"
displayName = "Vivecraft"
logoFile="vivecraft_icon.png"
authors = "NicBOMB, fayer3, Ferri_Arnus, IMS, jrbudda, minecraft player"
displayTest="IGNORE_SERVER_VERSION"
description = '''
The VR mod for any loader!
'''
updateJSONURL = "https://api.modrinth.com/updates/vivecraft/forge_updates.json"
#logoFile = ""

[[dependencies.vivecraft]]
modId = "forge"
mandatory = true
versionRange = "[46,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vivecraft]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"
